openapi: 3.0.1
info:
  title: pythagoras-node
  description: Node server for Pthg
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Endpoints
  description: Simple entry endpoints
- name: Specification
  description: The swagger API specification
paths:
  /entries:
    get:
      tags:
      - Entries
      description: Fetch all entries
      responses:
        200:
          description: Returns all entries
          content: {}
    post:
      tags:
      - Entries
      description: Create a new entry
      requestBody:
        description: an entry
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryBody'
        required: true
      responses:
        200:
          description: Returns all entries
          content: {}
  /entries/{id}:
    get:
      tags:
      - Entries
      parameters:
      - name: id
        in: path
        description: The id of the entry to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the entry with the specified id
          content: {}
        404:
          description: Entry not found
          content: {}
components:
  schemas:
    EntryBody:
      title: entry
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
   